LABEL_LIKELY_AI = (
    "Likely AI-generated — Our analysis found strong patterns consistent with "
    "machine-written text, including uniform structure and phrasing typical of "
    "AI tools. We're confident in this assessment."
)

LABEL_UNCERTAIN = (
    "Attribution unclear — This content shows mixed signals, and we can't "
    "confidently say whether it was written by a person or generated by AI. "
    "We're sharing this honestly rather than guessing."
)

LABEL_LIKELY_HUMAN = (
    "Likely human-written — Our analysis found natural variation in style and "
    "structure typical of original human creative work. We're confident this "
    "was not generated by AI."
)


def generate_label(confidence: float, attribution: str) -> str:
    if attribution == "likely_ai":
        return LABEL_LIKELY_AI
    if attribution == "likely_human":
        return LABEL_LIKELY_HUMAN
    return LABEL_UNCERTAIN
