import json
import os
import re

from groq import Groq

PROMPT_TEMPLATE = """You are an expert at distinguishing AI-generated text from human-written text.

Analyze the following text and assess how likely it is to have been generated by an AI language model versus written by a human.

Consider: sentence uniformity, hedging phrases, template-like structure, lack of personal voice, and overly balanced phrasing.

Respond with ONLY a JSON object in this exact format:
{{"ai_likelihood": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

Where 0.0 means almost certainly human-written and 1.0 means almost certainly AI-generated.

Text to analyze:
\"\"\"
{text}
\"\"\"
"""


def run_llm_signal(text: str) -> float:
    """Return a score from 0.0 (likely human) to 1.0 (likely AI)."""
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return _fallback_heuristic(text)

    client = Groq(api_key=api_key)
    prompt = PROMPT_TEMPLATE.format(text=text[:3000])

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=150,
    )

    raw = response.choices[0].message.content.strip()
    try:
        parsed = json.loads(raw)
        score = float(parsed["ai_likelihood"])
        return max(0.0, min(1.0, score))
    except (json.JSONDecodeError, KeyError, ValueError, TypeError):
        match = re.search(r"0\.\d+|1\.0|1|0", raw)
        if match:
            return max(0.0, min(1.0, float(match.group())))
        return 0.5


def _fallback_heuristic(text: str) -> float:
    """Simple keyword heuristic when no API key is available."""
    ai_phrases = [
        "it is important to note",
        "furthermore",
        "in conclusion",
        "paradigm shift",
        "stakeholders",
        "it is equally essential",
        "transformative",
        "various sectors",
    ]
    lower = text.lower()
    hits = sum(1 for phrase in ai_phrases if phrase in lower)
    return min(0.95, 0.4 + hits * 0.12)
